In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [2]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [3]:
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [5]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[::2])
print(a[1::])
print(a[2:,2:])
print(a[:2])
print(a[:2:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [2]:
reversed_array=arr[::-1]
print(reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [4]:
row1=[0,:]
print(row1)

SyntaxError: invalid syntax (4231433327.py, line 1)

In [5]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [6]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])

10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [8]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1=arr2))
print(result)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2215830054.py, line 3)

In [9]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
res=np.hstack((arr1,arr2))
print(res)
res1=np.hstack((arr1,arr2))
print(res1)
res2=np.dstack((arr1,arr2))
print(res2)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
res=np.split(arr,3)
print(res)
arr1=np.array([1,2,3,4,5])
res1=np.array.split(arr,3)
print(res1)
arr2=np.array([[1,2,3],[4,5,6]])
res2=np.hsplit(arr,3)
print(res2)
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
res3=np.vsplit(arr3,3)
print(res3)
res4=np.dsplit(arr)
print(res4)


[array([1, 2]), array([3, 4]), array([5, 6])]


AttributeError: 'builtin_function_or_method' object has no attribute 'split'